sudo: required
dist: trusty
language: node_js

notifications:
  email: false

node_js:
  - 'stable'

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - npm install -g gulp codecov
  - npm install

script:
  - ./node_modules/.bin/istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec
  - npm test
  - codecov
  - gulp build

after_success:
  - bash <(curl -s https://codecov.io/bash)
